### ISSUE TITLE
tokenize input string

### ISSUE THREAD

**Issue by CodyKat** [iijung/minishell#1]
first step of parse,

make liked list of tokens form input string that read from readline.

**Comment by iijung** [comment]
- [ ] Not interpret unclosed quotes or special characters which are not required by the subject such as `\` (backslash) or `;` (semicolon).
- [ ] Handle `’` (single quote) which should prevent the shell from interpreting the metacharacters in the quoted sequence.
- [ ] Handle `"` (double quote) which should prevent the shell from interpreting the metacharacters in the quoted sequence except for `$` (dollar sign).
- [ ] `&&` and `||` with parenthesis for priorities. **(bonus)**

**Comment by CodyKat** [comment]
before making tokens..I have to make parse grammar#9
