### ISSUE TITLE
[lexer] operator, redirection token type issue

### ISSUE THREAD

**Issue by CodyKat** [iijung/minishell#15]
#1 브랜치를 통해 만든 렉서는 operator라는 토큰 타입안에 "|" "||" "&" "&&" 4가지를 모두 인정해서 받고 있는데,
"&"같은 토큰은 지원하지 않을 문법이기때문에 lexer에서 string토큰으로 받아오거나 모호한 문법등으로 처리를 해야할 것 같고,(정해야함)
리다이렉션 토큰과 operator 토큰의 경우 data랑 len을 가져오기 보다는 세부 type enum을 사용하는게 더 좋을 것 같습니다.

**Comment by iijung** [comment]
is_lexeme(char *) 로 바꾸고 길이가 긴  ||  && 를 strncmp 로 먼저 체크 후 단일 어휘 체크하면 됩니다! 
원래 이런 구조였는데 코드가 복잡해보여서 줄였는데 목요일에 집 도착하면 바로 수정할게요!
