### ISSUE TITLE
마지막 리다이렉션만 처리되는 문제

### ISSUE THREAD

**Issue by CodyKat** [iijung/minishell#42]
구현요구사항 변경으로 모든 리다이렉션을 처리하도록 수정 필요

**Comment by iijung** [comment]
# 구현 명세
[] init_pipex.c 에서 리디렉션을 위한 구조체 생성 및 해제 
  - 리디렉션 타입
  - 리디렉션 파일명
  - 리디렉션 파일 디스크립터  # heredoc 미리 설정 필요
 [] run_pipex에서 리디렉션 리스트에 따라 순차적으로 stdin, stdout을 리디렉션
  - 리디렉션 중간에 HEREDOC 타입의 파일디스크립터가 -1 인 경우 EXIT_FAILURE 반환 
  - 리디렉션 중간에 실패하면 명령어를 수행하지 않고 EXIT_FAILURE 반환
  - 리디렉션이 성공하면 빌트인 및 명령어 실행

**Comment by iijung** [comment]
b5c077b

**Comment by iijung** [comment]
#54
