### ISSUE TITLE
cat 실행시 cat실행중 출력되지 않고 cat종료후 모두 출력되는 현상

### ISSUE THREAD

**Issue by CodyKat** [iijung/minishell#58]
아마 #56 과 관련있는 이슈인것 같음

minishell$ cat
a
b
c
aD (EOF입력과 동시에 aD가 출력)
b
c

**Comment by iijung** [comment]
**원인** : 마지막 파이프에 execute 하는 순간의 STDOUT_FILENO 을 설정한 뒤 리디렉션 처리해야 하는데 #42에서 모든 파이프라인이 끝난 뒤 읽도록 수정하면서 발생한 문제로 파악됨

**Comment by iijung** [comment]
이전 이슈와 동일한 문제이므로 이 이슈는 닫고 #56 에 작성하겠습니다
