### ISSUE TITLE
* 으로 시작하는 명령어 입력시 실행X, *토큰 memory leaks

### ISSUE THREAD

**Issue by CodyKat** [iijung/minishell#67]

**Comment by CodyKat** [comment]
_arg함수 리턴직전에
if (str[0] == '*')
	free(str);
코드를 추가하면 릭은 사라지지만 명령어가 실행되지 않는 문제는 여전함

**Comment by CodyKat** [comment]
디버그함수를 만들어 argl를 찍어본 결과:
argl-> *가 확장된 결과로 잘 들어가 있음

**Comment by CodyKat** [comment]
확장은 잘 되지만 첫번째 인자가 폴더명으로 들어가고, 폴더명이 명령어일때 에러메시지가 뜨지 않는 현상으로 파악

**Comment by CodyKat** [comment]
_exec_with_path 함수 첫 access에서 디렉토리 권한체크후 바로 execve를 시도함.
하지만 디렉토리라 execve 실패하여 -1반환후 실행프로세스 종료.

**Comment by iijung** [comment]
set_pipex.c 에서 combine_string을 결과로 wildcard를 수행하는데 아래와 같이 수행해야하는데 해제하는 코드가 없었습니다. 원인 수정해서 반영했습니다!

1. wildcard가 없거나 실패한 경우 combine_string을 컨텐츠로 사용
2. wildcard가 성공한 경우 combine_string을 해제하고 argl을 컨텐츠로 사용
