### ISSUE TITLE
parsing grammar

### ISSUE THREAD

**Issue by CodyKat** [iijung/minishell#9]
- to make LR parse, I have to make parsing grammar
input case : meta char(|, &, *, <, >), dquote, squote, IFS, lese_letter
token case : IFS, |, ||, &&, <, <<, >, >>, *, ", '

**Comment by CodyKat** [comment]
complete making first parsing grammar

**Comment by iijung** [comment]
# 어휘 항목
| lexeme | description                                   |
| ------ | --------------------------------------------- |
| \|     | 파이프                                        |
| *      | 파일 이름 확장 (wildcard)                     |
| (      | 우선순위 시작                                 |
| )      | 우선순위 종료                                 |
| <      | 리디렉션 입력                                 |
| >      | 리디렉션 출력 (overwrite)                     |
| >>     | 리디렉션 출력 (add)                           |
| <<     | hearedoc                                      |
| &&     | AND 연산                                      |
|        |                                               |  | OR 연산 |
| '      | 문자열 시작 및 종료 (모든 문자의 리터럴 유지) |
| "      | 문자열 시작 및 종료($제외하고 리터럴 유지)    |
| $      | 환경변수                                      |
| 공백   | IFS(Internal Field Separator)                 |
| 탭     | IFS(Internal Field Separator)                 |
| 개행   | IFS(Internal Field Separator)                 |

# 문법
```
S -> command
command -> (command)
command -> command operator command
operator -> &&
operator -> ||
operator -> |

command -> redirection command
command -> command redirection
redirection -> << string        // heredoc
redirection -> >> string        // addfile
redirection -> > string         // outfile
redirection -> < string         // infile

command -> argv
argv -> argv argv
argv -> parameter
argv -> *
parameter -> "parameter"
parameter -> parameter parameter
parameter -> $environment
parameter -> string

string -> 'string'
```

# 토큰 목록
| token       | lexeme        |
| ----------- | ------------- |
| parenthesis | (, )          |
| operator    | &&, \|\| , \| |
| redirection | <, >, >>, <<  |
| wildcard    | *             |
| dquote      | "             |
| quote       | '             |
| environment | $             |
| string      | 그 외 문자열  |
